### ISSUE TITLE
label got an empty value

### ISSUE THREAD

**Issue by vkompell** [hummerichsander/streamlit-free-text-select#1]
I have successfully used this. But when clearing the text and prior to submitting a question - i get this warning. Please suggest how can this be fixed. In other streamlit widgets they give this option of label_visibillity to handle this; but how can we resolve it here? Thank you very much.

`label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.

**Comment by hummerichsander** [comment]
I just implemented the "label_visibility" parameter and published it as a new version 0.1.1 on pypi.
